version: '3.9'
services:
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: always
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit

  db:
    image: 'postgres:13.7'
    container_name: server_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ['CMD-SHELL', 'su postgres', '&&', 'pg_isready']
      interval: 5s
      timeout: 5s
      retries: 10