version: '3.9'

volumes:
  postgres_data:

services:
  gateway:
    build:
      context: gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
    volumes:
      - "/etc/localtime:/etc/localtime:ro"

  server:
    build:
      context: server
      dockerfile: Dockerfile
    restart: always
    container_name: server
    expose:
      - 9090
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
    volumes:
      - "/etc/localtime:/etc/localtime:ro"

  db:
    image: 'postgres:13.7'
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'su postgres', '&&', 'pg_isready']
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_DB: shareit
      POSTGRES_PASSWORD: password
