CREATE TYPE IF NOT EXISTS booking_status AS ENUM (
    'WAITING',
    'APPROVED',
    'REJECTED',
    'CANCELLED'
);

CREATE TABLE IF NOT EXISTS users (
    user_id         bigint          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            text            NOT NULL,
    email           text            NOT NULL,
    PRIMARY KEY (user_id),
    UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests (
    request_id      bigint          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description     text            NOT NULL,
    requester_id    bigint          NOT NULL,
    created_at      timestamp without time zone
                                    NOT NULL,
    PRIMARY KEY (request_id),
    FOREIGN KEY (requester_id)
            REFERENCES users (user_id)
            ON DELETE CASCADE
            ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS items (
    item_id         bigint          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            text            NOT NULL,
    description     text            NOT NULL,
    available       bool            NOT NULL,
    owner_id        bigint          NOT NULL,
    request_id      bigint,
    PRIMARY KEY (item_id),
    FOREIGN KEY (owner_id)
            REFERENCES users (user_id)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    FOREIGN KEY (request_id)
            REFERENCES requests
            ON DELETE CASCADE
            ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
    booking_id      bigint          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date      timestamp without time zone
                                    NOT NULL,
    end_date        timestamp without time zone
                                    NOT NULL,
    item_id         bigint          NOT NULL,
    booker_id       bigint          NOT NULL,
    status          booking_status  NOT NULL,
    PRIMARY KEY (booking_id),
    FOREIGN KEY (item_id)
            REFERENCES items
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    FOREIGN KEY (booker_id)
            REFERENCES users (user_id)
            ON DELETE CASCADE
            ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS comments (
    comment_id      bigint          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text            text            NOT NULL,
    item_id         bigint          NOT NULL,
    author_id       bigint          NOT NULL,
    created         timestamp without time zone
                                    NOT NULL,
    PRIMARY KEY (comment_id),
    FOREIGN KEY (item_id)
            REFERENCES items
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    FOREIGN KEY (author_id)
            REFERENCES users (user_id)
            ON DELETE CASCADE
            ON UPDATE CASCADE
);